pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            agent {
                docker{
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
              environment {
        GOCACHE = '/tmp/go-cache'
    }
            steps {
               dir('bugtracker-backend'){
                sh 'go test -v ./...'
               }
            }
        }
    }
}