pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            steps {
               dir('bugtracker-backend'){
                sh 'go tests -v ./...'
               }
            }
        }
    }
}